USE BANK;

CREATE TABLE PERSON (
    PersonID INT PRIMARY KEY AUTO_INCREMENT,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    Email VARCHAR(100) UNIQUE,
    Phone VARCHAR(20),
    Address VARCHAR(255)
);

CREATE TABLE EMPLOYEE (
    EmployeeID VARCHAR (5) PRIMARY KEY,
    PersonID INT UNIQUE,
    BranchID VARCHAR,
    Position ENUM('Manager', 'Supervisor', 'Accountant', 'Loan Officer', 'Cashier', 'Security & Forensic'),
    FOREIGN KEY (PersonID) REFERENCES PERSON(PersonID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (BranchID) REFERENCES BRANCH(BranchID) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE CUSTOMER (
    CustomerID INT PRIMARY KEY AUTO_INCREMENT,
    PersonID INT UNIQUE,
    DateOfBirth DATE,
    FOREIGN KEY (PersonID) REFERENCES PERSON(PersonID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE BRANCH (
    BranchID VARCHAR PRIMARY KEY,
    BranchName VARCHAR(100) NOT NULL,
    Address VARCHAR(255) NOT NULL,
    City VARCHAR(50) NOT NULL,
    Phone VARCHAR(20)
);

CREATE TABLE ACCOUNT (
    AccountNumber INT PRIMARY KEY AUTO_INCREMENT,
    CustomerID INT,
    BranchID VARCHAR,
    AccountType ENUM('Saving', 'Student', 'Fixed_Deposit'),
    Balance DECIMAL(15,2) DEFAULT 0.00,
    OpeningDate DATE NOT NULL,
    FOREIGN KEY (CustomerID) REFERENCES CUSTOMER(CustomerID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (BranchID) REFERENCES BRANCH(BranchID) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE TRANSACTION (
    TransactionID INT PRIMARY KEY AUTO_INCREMENT,
    AccountNumber INT,
    Amount DECIMAL(15,2) NOT NULL,
    TransactionType ENUM('Deposit', 'Withdrawal', 'Transfer') NOT NULL,
    TransactionDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    Description TEXT,
    FOREIGN KEY (AccountNumber) REFERENCES ACCOUNT(AccountNumber) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE LOAN (
    LoanID INT PRIMARY KEY AUTO_INCREMENT,
    CustomerID INT,
    EmployeeID VARCHAR (5),
    LoanAmount DECIMAL(15,2) NOT NULL,
    InterestRate DECIMAL(5,2) NOT NULL,
    Status ENUM('Approved', 'Pending', 'Rejected') DEFAULT 'Pending',
    StartDate DATE NOT NULL,
    DueDate DATE NOT NULL,
    FOREIGN KEY (CustomerID) REFERENCES CUSTOMER(CustomerID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (EmployeeID) REFERENCES EMPLOYEE(EmployeeID) ON DELETE NO ACTION ON UPDATE NO ACTION
);
